name: Django Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  DJANGO_SETTINGS_MODULE: tests.settings

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 6
      matrix:
        # see https://docs.djangoproject.com/en/5.2/faq/install/
        python-version: ['3.10', '3.11', '3.12', '3.13']
        django-version: ['4.2.*', '5.2.*']
        include:
          - python-version: '3.8'
            django-version: '3.2.*'
          - python-version: '3.9'
            django-version: '4.2.*'
        exclude:
          - python-version: '3.13'
            django-version: '4.2.*'
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install 'Django==${{ matrix.django-version }}' coverage
        python manage.py makemigrations

    - name: Run Tests
      run: |
        coverage run --source='shortener' manage.py test
        coverage xml

    - name: Upload results to Codecov
      if: matrix.python-version == '3.13' && matrix.django-version == '5.2.*'
      uses: codecov/codecov-action@v5
      with:
        token: ${{ secrets.CODECOV_TOKEN }}
